---
$schemaver: '2.0'
deployables:
  - name: ical2json rest web serivce
    type: Web Service
    aliases:
    short_description:
    assignment_group: AD-Back End Technologies and Applications
    notes:
    maintained_by:
      - Wyatt Taylor
      - Travis Gengler
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit-appdev/ical-parser
        source_repo_url: https://github.com/test-ndpete-org/ical-parser
        swagger_urls:
    microservice: true
    technologies_used:
      - Java
      - Docker
      - AWS ECS
      - Tomcat
    stages:
        deprecated:
            urls:
                product_page:
                physical_url: http://ws.byu.edu/services/ical-parser
                virtual_url:
            hosting_location: BYU
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                      - Application Development
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
        stage:
            urls:
                product_page:
                physical_url: https://ical2json.devops.byu.edu/services/ical-parser/
                virtual_url:
            hosting_location: AWS
            aws_account: sla-dev-stg-ad-oit-byu
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                      - Application Development
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
        production:
            urls:
                product_page:
                physical_url: https://ical2json.mobile.byu.edu/services/ical-parser/
                virtual_url:
            hosting_location: AWS
            aws_account: beta-sla-ad-oit-byu
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                      - Application Development
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: Not Classified
        env: production
        team:
        app: ical2json rest web serivce
    federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/ical-parser/master/.repo-meta.yml
    x-anything:
