FROM tomcat:7-jre7
MAINTAINER TravisAGengler@gmail.com

ARG APPSTAGE
ARG SRC_BRANCH_A
ARG SRC_VER_A
ARG SRC_COMMIT_A
ARG SRC_TAGS_A

COPY target/ical.war /usr/local/tomcat/webapps/services#ical-parser.war
